NUMOJ/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from polls import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'problem', views.ProblemViewSet)
router.register(r'submission', views.SubmissionViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^polls/', include('polls.urls', namespace = 'polls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^pie$', views.demo_piechart, name='demo_piechart'),
    url(r'^login$', views.view_login, name='login'),
    url(r'^home$', views.index, name='index'),
    url(r'^level/(?P<l>[0-9]+)/(?P<page>[0-9]+)/$', views.level, name='level'),
    url(r'^problems$', views.problems, name='problems'),
    url(r'^problems/(?P<page>[0-9]+)/$', views.problems, name='problems'),
    url(r'^rank$', views.rank, name='rank'),
    
    url(r'^status/(?P<page>[0-9]+)/$', views.status, name='status'),
    url(r'^pstatus/(?P<pid>[0-9]+)/(?P<page>[0-9]+)/$', views.pstatus, name='pstatus'),

    # create
    url(r'^tag/(?P<tag_id>[0-9]+)/(?P<page>[0-9]+)/$', views.tag, name='tag'),
    url(r'^createTag/$', views.createTag, name='createTag'),
    url(r'^createTagAction/$', views.createTagAction, name='createTagAction'),
    
    url(r'^createUser/$', views.createUser, name='createUser'),
    url(r'^createUserAction/$', views.createUserAction, name='createUserAction'),

    url(r'^createProblem/$', views.createProblem, name='createProblem'),
    url(r'^createProblemAction/$', views.createProblemAction, name='createProblemAction'),
    
    # submit
    # ex: /polls/5/problem
    url(r'^problemN/(?P<problem_name>[a-z|\w |\W|0-9]+)/$', views.problemN, name='problemN'),
    url(r'^problem/(?P<problem_id>[0-9]+)/$', views.problem, name='problem'),
    url(r'^userN/(?P<user_name>[a-z|0-9]+)/$', views.userN, name='userN'),
    url(r'^user/(?P<user_id>[0-9]+)/$', views.user, name='user'),

    url(r'^submit/$', views.submit, name='submit'),
    url(r'^submitAction/$', views.submitAction, name='submitAction'),
]

polls/models.py
from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, Permission
import random

# Create your models here.
class Tag(models.Model):
    tagName = models.CharField(max_length = 60)
    
    def __str__(self):
        return self.tagName

class Problem(models.Model):
    tag = models.ManyToManyField(Tag)
    level = models.IntegerField(default = 3)
    problemName = models.CharField(max_length = 60)
    problemStatement = models.CharField(max_length = 60)
    problemDate = models.DateField(max_length = 1, auto_now = True)
    extraInformation = models.CharField(max_length = 1000)
    timelimit = models.FloatField(default = 1)
    input = models.CharField(max_length = 60, default = "null")
    output = models.CharField(max_length = 60, default = "null")
    
    def __str__(self):
        return self.problemName
    
class Submission(models.Model):
    type_status = (
        ('Accepted', 'AC'), ('Time limit exceeded', 'TLE'), ('Wrong answer', 'WA')
    )
    
    problem = models.ForeignKey(Problem)
    user = models.ForeignKey(User)
    status = models.CharField(max_length = 20, choices = type_status)
    submittedDate = models.DateTimeField(default=timezone.now)
    Language = models.CharField(default = "C++", max_length = 20)
    Time = models.FloatField(default = 0.0)
    Memory = models.IntegerField(default = 0)
    code = models.CharField(default = "..code..", max_length = 1000)

    def __str__(self):
        return self.user.username
    
    
class News(models.Model):
    title = models.CharField(max_length = 1000)
    time = models.DateTimeField(auto_now = True)
    news = models.CharField(max_length = 10000)
    
    def __str__(self):
        return self.news

polls/forms.py
# -*- coding: utf-8 -*-

from django import forms


class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file'
    )

polls/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from .models import Problem, Tag, News, Submission

# form .models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Permission
from django.db import connection
import random

def index(request):
    problem_list = Problem.objects.order_by('id')[:10]
    User_list = User.objects.order_by('id')
    Tag_list = Tag.objects.order_by('id')
    News_list = News.objects.order_by('id')

    if not request.session.get('member_id', None):
        return HttpResponseRedirect('/polls/login')
        request.session['member_id'] = 0

    member_id = request.session['member_id']
    
    add_Tag = False;

    user = User.objects.get(id = member_id)
    if user is not None:
        add_Tag = user.has_perm("add_Tag")

    context = {'problem_list': problem_list,
               'User_list': User_list, 'Tag_list': Tag_list, 
               'member_id': member_id, 'News_list': News_list,
               'add_Tag': add_Tag, 'top_rank_list': get_rank(0)}
    
    return render(request, 'polls/home.html', context)


def view_login(request):
    flag = False
    request.session['pro'] = 0
    request.session['member_id'] = 0

    logout(request)

    if request.method == 'POST':
        username = request.POST['name']
        password = request.POST['password']
        user = authenticate(username=username, password = password)
        user1 = user
        if user is not None:
            login(request, user)
            request.session['member_id'] = user.id
            return HttpResponseRedirect('/polls/user/' + str(user.id))
        
        else:
            flag = True;
            request.session['member_id'] = 0

    request.session['member_id'] = 0;
    context = {'flag': flag, 'member_id': 0, 'top_rank_list': get_rank(0)}
    return render(request, 'polls/login.html', context)


def problem(request, problem_id):
    member_id = request.session['member_id']
    problem = get_object_or_404(Problem, id = problem_id)
    top_rank_list = get_rank(0)
    request.session['pro'] = problem_id
    return render(request, 'polls/problem.html', {'problem': problem, 'member_id': member_id, 'top_rank_list':top_rank_list})


def problemN(request, problem_name):
    member_id = request.session['member_id']
    problem = get_object_or_404(Problem, problemName = problem_name)
    top_rank_list = get_rank(0)
    request.session['pro'] = problem.id
    return render(request, 'polls/problem.html', {'problem': problem, 'member_id': member_id, 'top_rank_list':top_rank_list})


def userN(request, user_name):
    user = get_object_or_404(User, username = user_name)
    member_id = request.session['member_id']
    top_rank_list = get_rank(0)
    return render(request, 'polls/user.html', {'user': user, 'member_id': member_id, 'top_rank_list': top_rank_list})


import datetime
from django.utils.timezone import utc
import json

def user(request, user_id):
    result = get_rank(1)
    user = get_object_or_404(User, id = user_id)
    member_id = request.session['member_id']
    top_rank_list = get_rank(0)
    
    rank = 0
    for x in result:
        if x['userName'] == user.first_name:
            rank = x['rank_index']
            solved = x['solved']

    AC = Submission.objects.filter(user = user).filter(status = "Accepted").count()
    WA = Submission.objects.filter(user = user).filter(status = "Wrong answer").count()
    TLE = Submission.objects.filter(user = user).filter(status = "Time limit exceeded").count()
    
    s = Submission.objects.filter(user = user).filter(status = "Accepted")
    Try = Submission.objects.filter(user = user).count()

    data = [0] * 32
    for x in s:
        data[x.submittedDate.day] = data[x.submittedDate.day] + 1;

    Data = []
    for d in range(1, 10):
        xx = str(12) + "." + str(d)
        Data.append({'x': xx, 'y': data[d]})

    return render(request, 'polls/user.html', {'solved': solved, 'Try': Try, 'Data': Data, 'rank': rank, 'user': user, 'member_id': member_id, 'top_rank_list': top_rank_list, 'AC': AC, 'WA':WA, 'TLE':TLE})


def createTag(request):
    return render(request, 'polls/createTag.html', {})


def createTagAction(request):
    name = request.POST['TagName']
    a = Tag(tagName = name)
    a.save()

    Tag_list = Tag.objects.order_by('id')
    context = {'Tag_list': Tag_list, 'name': name}
    
    return render(request, 'polls/createdTagResult.html', context)


def createUser(request):
    return render(request, 'polls/createUser.html', {})


def createUserAction(request):
    fname = request.POST['firstName']
    lname = request.POST['lastName']
    pword = request.POST['password']
    e = request.POST['email']
    s = request.POST['sex']
    
    a = User(firstName = fname, lastName = lname, password = pword,
             email = e, sex = s)
    a.save()
    
    User_list = User.objects.order_by('id')
    context = {'User_list': User_list, 'fname': fname}
    
    return render(request, 'polls/createdUserResult.html', context)


def createProblem(request):
    return render(request, 'polls/createProblem.html', {})


def createProblemAction(request):
    name = request.POST['name']
    st = request.POST['statement']
    i = request.POST['input']
    o = request.POST['output']
    t = request.POST['timelimit']
    e = request.POST['extra']
    a = Problem(problemName = name, problemStatement = st, timelimit = float(t), input = i, output = o,
                extraInformation = e)
    a.save()
    
    problem_list = Problem.objects.order_by('id')
    context = {'Problem_list': problem_list, 'problemName': name}
    
    return render(request, 'polls/createdProblemResult.html', context)

'''
for i in range(1, 100000):
    name = "problem " + str(i)
    st = "statement"
    i = "input"
    o = "output"
    t = 1.0
    e = "extraInformation"
    a = Problem(problemName = name, problemStatement = st, timelimit = float(t), input = i, output = o, extraInformation = e)
    a.save()

for i in range(2, 100):
    p = Problem.objects.get(id = random.randint(10, 100))
    u = User.objects.get(id = random.randint(2, 105))
    x = random.randint(1, 100)
    st = 'WA'
    if (x < 50): st = "TLE"
    if (x == 1): st = "AC"
    Submission(user = u, problem = p, status = st)
    Submission.save()    
'''

def get_rank(n):
    def dictfetchall(cursor): 
        desc = cursor.description 
        return [
            dict(zip([col[0] for col in desc], row)) 
            for row in cursor.fetchall()
        ]

    cursor = connection.cursor()
    if n != 0:
        cursor.execute("SELECT * FROM rank1")
    else:
        cursor.execute("SELECT * FROM rank1 LIMIT 10")
    result = dictfetchall(cursor)
    return result


def rank(request):
    result = get_rank(1)

    if not request.session.get('member_id', None):
        request.session['member_id'] = 0
    member_id = request.session['member_id']

    context = {'rank_list': result, 'member_id': member_id}
    
    return render(request, 'polls/rank.html', context)


def submit(request):
    top_rank_list = get_rank(0)
    if not request.session.get('pro', None):
        request.session['pro'] = 0;
    return render(request, 'polls/submit.html', {'member_id': request.session['member_id'], 'top_rank_list': top_rank_list, 'pro': request.session['pro']})

import os
import decimal
import math

def submitAction(request):
    user = User.objects.get(id = request.session['member_id'])
    problemId = request.POST['problemId']

    problem = Problem.objects.get(id = problemId)
    l = request.POST['lang']
    code = request.POST['code']
    
    inn = problem.input
    out = problem.output
    with open("input.txt", "w") as text_file:
        text_file.write(inn)
    with open("answer.txt", "w") as text_file:
        text_file.write(out)

    with open("ab.cpp", "w") as text_file:
        text_file.write(code)
    f = os.popen("python3 judge.py")
    temp = f.read()
    flag = temp.split('\n')[1]
    time = temp.split('\n')[0]

    a = Submission(user = user, problem = problem, Language = l, status = flag, code = code, Time = time)
    a.save()

    a = Submission.objects.filter(problem = problem).filter(user = user).order_by('-id')[:1]
    a = a[0]
    with open("Sub/" + str(a.id) + ".txt", "w") as text_file:
        text_file.write(code)
    
    return HttpResponseRedirect('/polls/status/1')

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def problems(request, page):
    problem_list = Problem.objects.order_by('id')
    paginator = Paginator(problem_list, 20)

    if not request.session.get('member_id', None):
        request.session['member_id'] = 0
    member_id = request.session['member_id']

    try:
        problem_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        problem_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        problem_list = paginator.page(paginator.num_pages)

    pTag = []
    solved = []
    iam = []
    if member_id != 0:
        user = User.objects.get(id = member_id)
    for x in problem_list:
        pTag.append(x.tag.all())
        solved.append(Submission.objects.filter(problem = x).filter(status = "Accepted").count())
        if member_id == 0:
            iam.append(0)
        elif member_id != 0:
            if Submission.objects.filter(problem = x).filter(status = "Accepted").filter(user = user).count() > 0:
                iam.append(1)
            elif Submission.objects.filter(problem = x).filter(user = user).count() > 0:
                iam.append(2)
            else :
                iam.append(0)

polls/templates/polls/Tag.html
{% extends "polls/home.html" %}

{% block Tag %}
<a href = "{% url 'polls:createTag'%}"> create tag </a>
<ul>
  
  {% for tag in Tag_list %}
  <li>
    {{tag.tagName}}
  </li>
  {% endfor %}
  
</ul>
{% endblock %}

polls/templates/polls/base.html
{% load staticfiles %}

<!DOCTYPE html>

<html>
<head>
    <link media="all" href="{% static '/polls/nv.d3.css' %}" type="text/css" rel="stylesheet" />
    <script type="text/javascript" src="{% static '/polls/d3.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/polls/nv.d3.min.js' %}"></script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <!-- Timeline CSS -->
    <script src="{% static 'polls/canvasjs.min.js' %}"></script>
    <script src="{% static 'polls/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'polls/Chart.js' %}"></script>
    <link href="{% static 'polls/dist/css/timeline.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'polls/dist/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'polls/mystyle.css' %}" rel="stylesheet">

	<!-- Bootstrap Core CSS -->
    <link href="{% static 'polls/bower_components/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'polls/bower_components/metisMenu/dist/metisMenu.min.css' %}" rel="stylesheet">

	<title>NUM OJ</title>

	    <!-- jQuery -->
    <script src="{% static 'polls/bower_components/jquery/dist/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'polls/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'polls/bower_components/metisMenu/dist/metisMenu.min.js' %}"></script>

    <!-- Morris Charts JavaScript -->
    <script src="{% static 'polls/bower_components/raphael/raphael-min.js' %}"></script>
    <script src="{% static 'polls/bower_components/morrisjs/morris.min.js' %}"></script>
    <script src="{% static 'polls/js/morris-data.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'polls/dist/js/sb-admin-2.js' %}"></script>

    <script src="{% static 'polls/js/morris-data.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'polls/dist/js/sb-admin-2.js' %}"></script>
    
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script src="{% static 'polls/myjs.js' %}"></script>                                                                                                           
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.oesmith.co.uk/morris-0.5.1.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.2/raphael-min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.0/morris.min.js"></script>

    </script>
</head>

<body>
	<div id="wrapper">
		<!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        	<!-- nav header -->
        	<div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="{% static 'polls/images/num.png' %}" style="padding-top: 10px; float: left; padding-left: 10px">
                <a class="navbar-brand" href="{% url 'polls:index' %}" style="color: #1178bb; padding-top: 20px" >
                    NUM Online Judge
                </a>
            </div>
            <!-- top menu-->
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <!--li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <img src="{% static 'polls/icons/64/magnifier.png' %}" height="18px">
                            </button>
                        </span>
                        </div>
                        
                    </li-->
                    <li><a href="{% url 'polls:problems' 1 %}"><img src="{% static 'polls/icons/64/game93.png' %}" class="icon"> Бодлогууд</a></li>
                    <li><a href="{% url 'polls:rank'%}"><img src="{% static 'polls/icons/64/ranking.png' %}" class="icon"> Чансаа</a></li> 
                    <li><a href="{% url 'polls:submit'%}"><img src="{% static 'polls/icons/64/send4.png' %}" class="icon"> Илгээх</a></li> 
                    <li><a href="{% url 'polls:status' 1 %}"><img src="{% static 'polls/icons/64/lifeline6.png' %}" class="icon"> Үр дүн</a></li> 
                    <li class="dropdown" style="padding-right: 20px">
                        {% if member_id != 0 %}
                            <a class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{% static 'polls/icons/64/user168.png' %}" class="icon"> Хэрэглэгч
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li>
                                    <a href="{% url 'polls:user' member_id %}"><img src="{% static 'polls/icons/64/user168.png' %}" class="icon"> Хувийн мэдээлэл </a>
                                </li>
                                <li><a href="#"><img src="{% static 'polls/icons/64/wrench1.png' %}" class="icon"> Хувийн мэдээлэл засварлах </a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="{% url 'polls:login'%}"><img src="{% static 'polls/icons/64/logout13.png' %}" class="icon"> Гарах</a>
                                </li>
                            </ul>
                        {% else %}
                            <a href="{% url 'polls:login' %}">
                                <img src="{% static 'polls/icons/64/user168.png' %}" class="icon"> 
                                Нэвтрэх
                            </a>
                        {% endif %}
                        <!-- /.dropdown-user -->
                    </li>
                </ul>
            </div>
        </nav>
        <div id="container" style="padding-top: 0px">
            <div class="row">
                <center>
                    <div style="col-md-8 col-md-offset-4"> 
                        {% block rank %}{% endblock %}
                    </div>
                </center>
                <div class="col-md-9">
                        {% block News %}{% endblock %}
                        {% block Tag %}{% endblock %}
                        {% block login %}{% endblock %}
                        {% block problem %}{% endblock %}
                        {% block problems %}{% endblock %}
                        {% block submit %}{% endblock %}
                        {% block profile %}{% endblock %}
                </div>
                <div class="col-md-3" style="padding-left: 30px; padding-top: 13px">
                    <center>
                        {# sidebar top rating#}
                        {% if top_rank_list %}
                        <div class="side">
                            <div>
                                <div class="side_header_left">
                                </div>
                                <div class="side_header">
                                    Чансаа тэргүүлэгчид
                                </div>
                            </div>
                            <table width="100%" border="1">
                                <thead>
                                    <tr>
                                        <th width="50px" style="text-align: center;">#</th>
                                        <th style="text-align: center;">Хэрэглэгч</th>
                                        <th width="70px" style="text-align: center;">Бодсон</th>
                                    </tr>
                                </thead>
                              {% for rank in top_rank_list %}
                              <tr>
                                <td style="text-align: center;"> {{rank.rank_index}} </td>
                                <td> 
                                    <a href="{% url 'polls:user' rank.userId %}" style="float: left; padding-left: 10px; ">{{ rank.userName }}</a>
                                </td>
                                <td style="text-align: center;"> {{rank.solved}}</td>
                              </tr>
                              {% endfor %}
                            </table>
                        </div>
                        {% endif %}
                    </center>
                    <center>
                        {# sidebar top rating#}
                        {% if pStatus %}
                        <div class="side">
                            <div>
                                <div class="side_header_left">
                                </div>
                                <div class="side_header">
                                    Үр дүн
                                </div>
                            </div>
                            <table width="100%" border="1">
                                <thead>
                                    <tr>
                                        <th width="50px" style="text-align: center;">#</th>
                                        <th style="text-align: center;">Хэрэглэгч</th>
                                        <th width="70px" style="text-align: center;">Бодсон</th>
                                    </tr>
                                </thead>
                              {% for rank in top_rank_list %}
                              <tr>
                                <td style="text-align: center;"> {{rank.rank_index}} </td>
                                <td> 
                                    <a href="{% url 'polls:user' rank.userId %}" style="float: left; padding-left: 10px; ">{{ rank.userName }}</a>
                                </td>
                                <td style="text-align: center;"> {{rank.solved}}</td>
                              </tr>
                              {% endfor %}
                            </table>
                        </div>
                        {% endif %}
                    </center>

                </div>
            </div>
        </div>
	</div>
</body>
</html>

polls/templates/polls/createProblem.html
<h1>create problem</h1>
<form action="{% url 'polls:createProblemAction' %}" method="post">
  {% csrf_token %}
  
  <label for="Name">Name</label>
  <input type="text" name="name">
  <label for="Statement">statement</label>
  <input type="text" name="statement">
  <label for="input">input</label>
  <input type="text" name="input">
  <label for="ouput">output</label>
  <input type="text" name="output">
  <label for="timelimit">timelimit</label>
  <input type="text" name="timelimit">
  <label for="extra">extraInformation</label>
  <input type="text" name="extra">
<input type="submit" value="create" />
</form>

polls/templates/polls/createUser.html
<h1>create user</h1>

<form action="{% url 'polls:createUserAction' %}" method="post">
  {% csrf_token %}
  
  <label for="firstName">firstName</label>
  <input type="text" name="firstName">
  <label for="lastName">lastName</label>
  <input type="text" name="lastName">
  <label for="password">password</label>
  <input type="text" name="password">
  <label for="email">email</label>
  <input type="text" name="email">
  <label for="sex">sex</label>
  <input type="text" name="sex">
  
<input type="submit" value="create" />
</form>

polls/templates/polls/home.html
{% extends "polls/base.html" %}

{% block News %}

	{% for news in News_list %}
		<div class="news">
			<h1>{{news.title}}</h1>
			<p>{{news.news}}</p>
			<h3>{{news.time}}</h3>
		</div>
	{% endfor %}

	<hr>

	{% if add_Tag %}
		<a href = "{% url 'polls:createTag'%}"> create tag </a>
	{% endif %}
	
	<ul>
		{% for tag in Tag_list %}
		<li>
		  {{tag.tagName}}
		</li>
	    {% endfor %}
	</ul>
{% endblock %}

polls/templates/polls/problems.html
{% extends "polls/base.html" %}

{% block problems %}
    
    {% if problem_list %}
	    <center>
		    <div class="content">
			    <h3 style="margin-bottom: 0px">
			    	Бодлогууд
			    </h3>
		    	<table class="table table-striped" width="100%">
				  <tr> 
				  	<th width="50px" style="text-align: center;">#</th>
				  	<th style="text-align: center;">Нэр</th>
				  	<th width="70px" style="text-align: center;">Түвшин</th>
				  	<th width="70px" style="text-align: center;">Бодсон</th>
				  </tr>
				  {% for item1, item2, item3, item4 in list %}
				  <tr
				  	{% if item4 == 1 %} 
				  		class="success"
				  	{% elif item4 == 2%}
				  		class="danger"
				  	{% endif %}
				  	>
				  	<td style="text-align: center;"> {{item1.id}} </td>
				    <td> 
				    	<a href="{% url 'polls:problem' item1.id %}" style="float: left; padding-left: 10px; ">{{ item1.problemName }}</a>
				    	{% for x in item2 %}
				    		<a href="{% url 'polls:tag' x.id 1 %}" style="float: right; padding-right: 10px; ">
				    			<span class="badge">{{x}}</span>
				    		</a>
				    	{% endfor %}
				   	</td>
				   	<td style="text-align: center;"><a href="{% url 'polls:level' item1.level 1 %}">{{ item1.level }}</a></td>
				   	<td style="text-align: center;"><a href="{% url 'polls:pstatus' item1.id 1 %}">{{item3}}</a></td>
				  </tr>
				  {% endfor %}
				</table>
			
			</div>
			<div class="pagination">
			    <span class="step-links">
			    	<ul class="pager">
				        {% if problem_list.has_previous %}
	  						<li class="previous">
						            <a href="{% url 'polls:problems' problem_list.previous_page_number %} ">Өмнөх</a>
					        </li>
				        {% endif %}

						<ul class="pagination" style="margin-top: 0px">
							{% for i in pages %}
								{% if i == problem_list.number %}
									<li class="active"><a href="{% url 'polls:problems' i %}">{{i}}</a></li>
								{% elif i == 0 %}
									<li class="disabled"><a href="{% url 'polls:problems' 1 %}">...</a></li>
								{% else %}		
									<li><a href="{% url 'polls:problems' i %}">{{i}}</a></li>
								{% endif %}
							{% endfor %}
	  					</ul>
  						
						{% if problem_list.has_next %}
	  						<li class="next"><a href="{% url 'polls:problems' problem_list.next_page_number %} ">Дараах</a></li>
				        {% endif %}
					</ul>
			        
			    </span>
			</div>
		</center>
	{% else %}
		<p>No polls are available.</p>
	{% endif %}

	{% if add_problem %}
		<a href = "{% url 'polls:createProblem' %}"> create Problem </a>
	{% endif%}
{% endblock %}